print("---- DIFERENÇA DO PRODUTO ENTRE 4 NÚMEROS ----\n")
A = int(input("Digite o primeiro número: "))
B = int(input("Digite o segundo número: "))
C = int(input("Digite o terceiro número: "))
D = int(input("Digite o quarto número: "))
DIFERENCA = (A * B - C * D)
print("\nDIFERENÇA =",DIFERENCA)